### ISSUE TITLE
"...for the birds." animation not completing

### ISSUE THREAD

**Issue by brad-arnett** [encryptic-team/encryptic-website#3]
I pushed the work you've done to the main site tonight.  Too excited to wait.

It's handling pretty well for being a maiden deployment, however, I'm seeing the animation get cut off a little early in Linux Firefox.  It keeps blinking but just stops where the image below shows it stopping at.  I think it's a browser thing because Chromium works and Firefox on Windows works (so maybe font related?) but I figured I'd say something here just in case you had any thoughts.

Example:
![archlabs_2019-03-07-12_3840x1080](https://user-images.githubusercontent.com/1466660/54011260-7a289f00-4137-11e9-95aa-89cfad8c82a7.png)

Firefox Quantum 65.0.2 64-bit
Linux icarus 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux

I tried it a second time with all add-ons disabled, and in safe mode to the same effect.

**Comment by Prune2000** [comment]
Hi @daed ! Thank you :) 

The length of the animation is supposed to land perfectly at the end of the sentence, but not sure why it wouldn't work on this browser. I'll look into it.

I notice on your screenshot that the arrow is a lot higher than it should be, and the text could be bigger. I created media queries for screen width that are bigger than 1900px. Could you tell me your screen resolution if you don't mind? I can probably reduce the width for the media queries down to 1800 or 1700px.

Thanks again!

**Comment by brad-arnett** [comment]
brad@icarus ~ % xrandr | grep " connected"
DP-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 509mm x 286mm
DP-3 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
brad@icarus ~ % xdpyinfo | grep dots
  resolution:    96x96 dots per inch

I just checked my MBP (Mojave and Firefox, same version) and it stops cleanly right after the "S" in BIRDS, but it doesn't display the period.  The retina display does weird things as far as deciphering the actual current resolution of the screen but I think it's effectively 2880x1800.  I'm honestly not sure how to figure the actual dpi there, but I don't know if that's actually relevant to the issue either.

Chrome 72.0.3626.121 64-bit on Mojave appears to display the animation correctly as well.
